sonar.projectKey=btc-predictor
sonar.projectName=BTC Predictor
sonar.host.url=http://localhost:9000
sonar.sources=shared/shared,api-service/api,workers
sonar.tests=shared/tests,api-service/tests,workers/fetch_price/tests,workers/daily/tests
sonar.language=py
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/alembic/**,**/versions/**,**/tests/**
sonar.test.inclusions=**/tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
