"""create models table

Revision ID: 493113cf244f
Revises: f1a0ccb22366
Create Date: 2026-05-17 07:54:00.673240

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "493113cf244f"
down_revision: str | Sequence[str] | None = "f1a0ccb22366"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Model name (e.g., 'linear_v1', 'lstm_v1')",
        ),
        sa.Column(
            "version",
            sa.String(length=50),
            nullable=False,
            comment="Model version (e.g., '1.0.0', '2024-05-17-001')",
        ),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Training hyperparameters as JSON (e.g., {'window_days': 30})",
        ),
        sa.Column(
            "artifact",
            sa.LargeBinary(),
            nullable=False,
            comment="Serialized model (pickle format)",
        ),
        sa.Column(
            "trained_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When training completed",
        ),
        sa.Column(
            "train_from", sa.Date(), nullable=False, comment="Training data start date"
        ),
        sa.Column(
            "train_to", sa.Date(), nullable=False, comment="Training data end date"
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether this model is currently active for predictions",
        ),
        sa.CheckConstraint("train_to >= train_from", name="valid_training_period"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="unique_model_version"),
    )
    op.create_index(op.f("ix_models_name"), "models", ["name"], unique=False)
    # Partial index for efficiently querying active models
    op.create_index(
        "idx_models_active",
        "models",
        ["name", "is_active"],
        unique=False,
        postgresql_where=sa.text("is_active = TRUE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_models_active", table_name="models")
    op.drop_index(op.f("ix_models_name"), table_name="models")
    op.drop_table("models")
    # ### end Alembic commands ###
