"""add multiple pnl strategies to predictions

Revision ID: d176f9ffb6cb
Revises: 6a9f03718b72
Create Date: 2026-05-18 21:07:01.399595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd176f9ffb6cb'
down_revision: Union[str, Sequence[str], None] = '6a9f03718b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('models', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment="Training hyperparameters as JSON (e.g., {'window_days': 30})",
               existing_nullable=False)
    op.drop_index(op.f('idx_models_active'), table_name='models', postgresql_where='(is_active = true)')
    op.add_column('predictions', sa.Column('pnl_long_short', sa.NUMERIC(precision=11, scale=2), nullable=True, comment='PnL from long/short symmetric strategy: long if UP, short if DOWN'))
    op.add_column('predictions', sa.Column('pnl_threshold', sa.NUMERIC(precision=11, scale=2), nullable=True, comment='PnL with threshold filter: only trade if predicted change > 1%'))
    op.add_column('predictions', sa.Column('pnl_realistic', sa.NUMERIC(precision=11, scale=2), nullable=True, comment='PnL with trading fees (0.1%) and stop-loss (2% max loss)'))
    op.alter_column('predictions', 'pnl_simulated',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.NUMERIC(precision=11, scale=2),
               existing_comment='Simulated profit/loss from trading strategy (in USDT)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'pnl_simulated',
               existing_type=sa.NUMERIC(precision=11, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='Simulated profit/loss from trading strategy (in USDT)',
               existing_nullable=True)
    op.drop_column('predictions', 'pnl_realistic')
    op.drop_column('predictions', 'pnl_threshold')
    op.drop_column('predictions', 'pnl_long_short')
    op.create_index(op.f('idx_models_active'), 'models', ['name', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('models', 'params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment="Training hyperparameters as JSON (e.g., {'window_days': 30})",
               existing_nullable=False)
    # ### end Alembic commands ###
