"""create btc_prices table

Revision ID: f1a0ccb22366
Revises: 
Create Date: 2026-05-16 14:01:20.409898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a0ccb22366'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Price timestamp in UTC'),
    sa.Column('open', sa.NUMERIC(precision=18, scale=8), nullable=False, comment='Opening price in USDT'),
    sa.Column('high', sa.NUMERIC(precision=18, scale=8), nullable=False, comment='Highest price in USDT'),
    sa.Column('low', sa.NUMERIC(precision=18, scale=8), nullable=False, comment='Lowest price in USDT'),
    sa.Column('close', sa.NUMERIC(precision=18, scale=8), nullable=False, comment='Closing price in USDT'),
    sa.Column('volume', sa.NUMERIC(precision=18, scale=8), nullable=False, comment='Trading volume in BTC'),
    sa.Column('source', sa.String(length=50), nullable=False, comment="Data source (e.g., 'binance')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_btc_prices_timestamp'), 'btc_prices', ['timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_btc_prices_timestamp'), table_name='btc_prices')
    op.drop_table('btc_prices')
    # ### end Alembic commands ###
